version: 2
models:
  - name: stg_spread
    columns:
      - name: ano_mes
        tests:
          - not_null
          - unique
      - name: spread_pf
        tests:
          - not_null

  - name: stg_inadimplencia
    columns:
      - name: ano_mes
        tests:
          - not_null
          - unique
      - name: inadimp_pf
        tests:
          - not_null

  - name: stg_concessoes
    columns:
      - name: ano_mes
        tests:
          - not_null
          - unique
      - name: concess_pf
        tests:
          - not_null
